#!/usr/bin/env bash
# Generate all auto-generatable secrets and write them to .env.
# Only VPS_IP is left for you to fill in (it's preserved if .env already has it).
#
# Re-run any time to ROTATE keys. The previous .env is backed up first.
# After running: set VPS_IP (if blank), then ./render.sh.
#
# Uses local `sing-box` / `wg` if installed, otherwise Docker.
set -euo pipefail
cd "$(dirname "$0")"

SINGBOX_IMAGE="ghcr.io/sagernet/sing-box:v1.13.13"

singbox() {
  if command -v sing-box >/dev/null 2>&1; then sing-box "$@"
  elif command -v docker >/dev/null 2>&1; then docker run --rm "$SINGBOX_IMAGE" "$@"
  else echo "ERROR: need either 'sing-box' or 'docker' installed." >&2; exit 1; fi
}

# Emit "<private> <public>" for a fresh WireGuard keypair.
gen_wg() {
  if command -v wg >/dev/null 2>&1; then
    local priv; priv=$(wg genkey)
    printf '%s %s\n' "$priv" "$(printf '%s' "$priv" | wg pubkey)"
  elif command -v docker >/dev/null 2>&1; then
    docker run --rm alpine sh -c \
      'apk add -q wireguard-tools >/dev/null 2>&1; p=$(wg genkey); printf "%s %s\n" "$p" "$(printf "%s" "$p" | wg pubkey)"'
  else
    echo "ERROR: need either 'wg' or 'docker' installed." >&2; exit 1
  fi
}

echo "Generating secrets..."

VLESS_UUID=$(singbox generate uuid)

# WebSocket path — a random hard-to-guess path so the endpoint isn't trivially
# discoverable by probing. Leading slash required.
WS_PATH="/$(singbox generate rand 8 --hex)"

read -r VPS_WG_PRIVATE_KEY VPS_WG_PUBLIC_KEY < <(gen_wg)
read -r HOME_WG_PRIVATE_KEY HOME_WG_PUBLIC_KEY < <(gen_wg)

# Sanity: nothing came back empty.
for v in VLESS_UUID WS_PATH \
         VPS_WG_PRIVATE_KEY VPS_WG_PUBLIC_KEY HOME_WG_PRIVATE_KEY HOME_WG_PUBLIC_KEY; do
  [ -n "${!v}" ] || { echo "ERROR: generation produced empty $v" >&2; exit 1; }
done

# Preserve existing manual values (VPS_IP, DOMAIN, ACME_EMAIL); back up any
# existing .env before overwriting.
VPS_IP=""
DOMAIN=""
ACME_EMAIL=""
if [ -f .env ]; then
  VPS_IP=$(awk -F= '/^VPS_IP=/{sub(/^VPS_IP=/,""); print; exit}' .env)
  DOMAIN=$(awk -F= '/^DOMAIN=/{sub(/^DOMAIN=/,""); print; exit}' .env)
  ACME_EMAIL=$(awk -F= '/^ACME_EMAIL=/{sub(/^ACME_EMAIL=/,""); print; exit}' .env)
  backup=".env.bak.$(date +%Y%m%d-%H%M%S)"
  cp .env "$backup"
  echo "Existing .env backed up to $backup"
fi

cat > .env <<EOF
# Generated by gen-secrets.sh. VPS_IP, DOMAIN, ACME_EMAIL are the manual values.
# .env is gitignored — never commit it.

# VPS public IP (or hostname) — fill this in. Used by wg0.conf Endpoint
# (home dials the VPS directly for the WireGuard leg).
VPS_IP=${VPS_IP}

# Your domain, DNS A/AAAA -> VPS IP (Cloudflare grey-cloud / DNS-only, or any
# DNS provider). The phone connects to this; sing-box gets a Let's Encrypt cert
# for it via ACME. Fill this in.
DOMAIN=${DOMAIN}

# Email for Let's Encrypt registration/expiry notices. Fill this in.
ACME_EMAIL=${ACME_EMAIL}

# VLESS over WebSocket + TLS
VLESS_UUID=${VLESS_UUID}
WS_PATH=${WS_PATH}

# WireGuard keypairs
VPS_WG_PRIVATE_KEY=${VPS_WG_PRIVATE_KEY}
VPS_WG_PUBLIC_KEY=${VPS_WG_PUBLIC_KEY}
HOME_WG_PRIVATE_KEY=${HOME_WG_PRIVATE_KEY}
HOME_WG_PUBLIC_KEY=${HOME_WG_PUBLIC_KEY}
EOF

chmod 600 .env
echo "Wrote .env"
[ -n "$VPS_IP" ] || echo "NOTE: VPS_IP is blank — set it in .env."
[ -n "$DOMAIN" ] || echo "NOTE: DOMAIN is blank — set it in .env."
[ -n "$ACME_EMAIL" ] || echo "NOTE: ACME_EMAIL is blank — set it in .env."
{ [ -n "$VPS_IP" ] && [ -n "$DOMAIN" ] && [ -n "$ACME_EMAIL" ]; } && echo "Next: ./render.sh"
