#!/usr/bin/env bash
# Generate all auto-generatable secrets and write them to .env.
# Only VPS_IP is left for you to fill in (it's preserved if .env already has it).
#
# Re-run any time to ROTATE keys. The previous .env is backed up first.
# After running: set VPS_IP (if blank), then ./render.sh.
#
# Uses local `sing-box` / `wg` if installed, otherwise Docker.
set -euo pipefail
cd "$(dirname "$0")"

SINGBOX_IMAGE="ghcr.io/sagernet/sing-box:v1.13.13"

singbox() {
  if command -v sing-box >/dev/null 2>&1; then sing-box "$@"
  elif command -v docker >/dev/null 2>&1; then docker run --rm "$SINGBOX_IMAGE" "$@"
  else echo "ERROR: need either 'sing-box' or 'docker' installed." >&2; exit 1; fi
}

# Emit "<private> <public>" for a fresh WireGuard keypair.
gen_wg() {
  if command -v wg >/dev/null 2>&1; then
    local priv; priv=$(wg genkey)
    printf '%s %s\n' "$priv" "$(printf '%s' "$priv" | wg pubkey)"
  elif command -v docker >/dev/null 2>&1; then
    docker run --rm alpine sh -c \
      'apk add -q wireguard-tools >/dev/null 2>&1; p=$(wg genkey); printf "%s %s\n" "$p" "$(printf "%s" "$p" | wg pubkey)"'
  else
    echo "ERROR: need either 'wg' or 'docker' installed." >&2; exit 1
  fi
}

echo "Generating secrets..."

VLESS_UUID=$(singbox generate uuid)
REALITY_SHORT_ID=$(singbox generate rand 8 --hex)

reality=$(singbox generate reality-keypair)
REALITY_PRIVATE_KEY=$(printf '%s\n' "$reality" | awk '/PrivateKey/{print $2}')
REALITY_PUBLIC_KEY=$(printf '%s\n' "$reality" | awk '/PublicKey/{print $2}')

read -r VPS_WG_PRIVATE_KEY VPS_WG_PUBLIC_KEY < <(gen_wg)
read -r HOME_WG_PRIVATE_KEY HOME_WG_PUBLIC_KEY < <(gen_wg)

# Sanity: nothing came back empty.
for v in VLESS_UUID REALITY_SHORT_ID REALITY_PRIVATE_KEY REALITY_PUBLIC_KEY \
         VPS_WG_PRIVATE_KEY VPS_WG_PUBLIC_KEY HOME_WG_PRIVATE_KEY HOME_WG_PUBLIC_KEY; do
  [ -n "${!v}" ] || { echo "ERROR: generation produced empty $v" >&2; exit 1; }
done

# Preserve an existing VPS_IP; back up any existing .env before overwriting.
VPS_IP=""
if [ -f .env ]; then
  VPS_IP=$(awk -F= '/^VPS_IP=/{sub(/^VPS_IP=/,""); print; exit}' .env)
  backup=".env.bak.$(date +%Y%m%d-%H%M%S)"
  cp .env "$backup"
  echo "Existing .env backed up to $backup"
fi

cat > .env <<EOF
# Generated by gen-secrets.sh. VPS_IP is the only manual value.
# .env is gitignored — never commit it.

# VPS public IP (or hostname) — fill this in.
VPS_IP=${VPS_IP}

# VLESS + REALITY
VLESS_UUID=${VLESS_UUID}
REALITY_PRIVATE_KEY=${REALITY_PRIVATE_KEY}
REALITY_PUBLIC_KEY=${REALITY_PUBLIC_KEY}
REALITY_SHORT_ID=${REALITY_SHORT_ID}

# WireGuard keypairs
VPS_WG_PRIVATE_KEY=${VPS_WG_PRIVATE_KEY}
VPS_WG_PUBLIC_KEY=${VPS_WG_PUBLIC_KEY}
HOME_WG_PRIVATE_KEY=${HOME_WG_PRIVATE_KEY}
HOME_WG_PUBLIC_KEY=${HOME_WG_PUBLIC_KEY}
EOF

chmod 600 .env
echo "Wrote .env"
[ -n "$VPS_IP" ] || echo "NOTE: VPS_IP is blank — set it in .env, then run ./render.sh"
[ -n "$VPS_IP" ] && echo "Next: ./render.sh"
